name: 'Martini Upload Package'
description: 'Prepares and uploads a package to a Martini instance'
author: 'Rafal Janicki <rafal.janicki@torocloud.com>'
inputs:
  base_url:
    description: 'Base URL of the Martini instance'
    required: true
  access_token:
    description: "Access token of Martini which can be obtained from your instance or Lonti Console"
    required: true
  package_dir:
    description: "Path to a directory that contains the package's files"
    required: false
    default: ''
outputs:
  id:
    description: 'ID of the uploaded package'
  name:
    description: 'Name of the uploaded package'
  status:
    description: 'Status of the uploaded package'
  version:
    description: 'Version of the uploaded package'
runs:
  using: 'node20'
  main: 'dist/index.js'