name: 'Martini Upload Package'
description: 'Prepares and uploads packages to a Martini instance'
author: 'Rafal Janicki <rafal.janicki@torocloud.com>'

inputs:
  BASE_URL:
    description: 'Base URL of the Martini instance'
    required: true
  MARTINI_ACCESS_TOKEN:
    description: 'Access token of the Martini instance'
    required: true
  PACKAGE_DIR:
    description: 'Path to the directory containing package folders'
    required: false
    default: 'packages'
  PACKAGE_NAME_PATTERN:
    description: 'Regex pattern to match package directories'
    required: false
    default: '.*'
  MAX_ATTEMPTS:
    description: 'Max number of polling attempts for package status'
    required: false
    default: '6'
  POLL_PACKAGE:
    description: 'Name of a specific package to poll (optional)'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'